# Generated by Django 5.1.11 on 2025-08-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('room_number', models.CharField(max_length=10)),
                ('complaint_type', models.CharField(choices=[('carpentry', 'Carpentry'), ('electricity', 'Electricity'), ('plumbing', 'Plumbing'), ('sanitary', 'Sanitary'), ('civil', 'Other Civil Works')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
